authors:
  sam:
    name: Sam
    description: Group member
    avatar: https://robohash.org/sam?set=set4&bgset=&size=400x400

  rich:
    name: Rich
    description: Group member
    avatar: https://robohash.org/rich?set=set4&bgset=&size=400x400
    
  