authors:
  sam:
    name: Sam
    description: Group member
    avatar: https://github.com/yuetau.png

  rich:
    name: Rich
    description: Group member
    avatar: https://robohash.org/1c8e8a6e8d1fe52b782b280909abeb38?set=set4&bgset=&size=400x400
    
  